export default {
  "token":"Token",
  "faq": "FAQ",
  "rate": "Rate",
  "connect_wallet": "Connect wallet",
  "enter_to_profile":"Login to profile",
  "menu":"Menu",
  "close":"Close",
  "profile":"Profile",
  "balance": "Balance",
  "wallet": "Wallet for withdraw",
  "personal": "Personal information",
  "history": "Transactions history",
  "security": "Security",
  "support": "Support",
  "tokens_on_balance": "OVP-tokens on your balance",
  "by_current_rate": "at the current rate",
  "tokens_price_on_balance":"The cost of tokens on the balance",
  "grows_from": "total increase in value for the entire period from",
  "grows_to": "to",
  "wallet_label":"To be able to withdraw tokens to your crypto wallet, specify its address",
  "save_wallet":"Save withdrawal address",
  "supported_wallet":"Supported Wallets",
  "supported_wallet_desc":"OVP tokens can be stored on all crypto wallets supporting the ERC-20 network ",
  "wallet_create": "Address saved",
  "already_exists": "Already exists",
  "required": "required",
  "error": "Unknown error",
  "updated": "Updated",
  "save": "Save",
  "firstname": "Name",
  "lastname": "Lastname",
  "middlename": "Middlename",
  "address": "Address",
  "birthday": "Birthday",
  "phone": "Phone",
  "wrong_password": "Wrong password",
  "old_password": "Old password",
  "new_password": "New password",
  "password": "Password",
  "retype_password": "Repeat password",
  "passwor_requirment_1": "Password length must be at least 8 characters",
  "passwor_requirment_2": "The password must not contain a sequence of characters that is part of the login",
  "passwor_requirment_3": "Password must not be the same as previous passwords",
  "must_match": "must match",
  "message_send": "Message send",
  "explane_problem": "Describe the question or problem",
  "ask_question": "Ask a Question",
  "question": "Appeal",
  "response": "Support response",
  "wrong_password_email": "Wrong password or email",
  "login":"Login",
  "register":"Registration",
  "do_register":"Register",
  "user_exists": "User already exists",
  "i_forgot_password": "I forgot my password",
  "forgot_password":"Forgot password",
  "forgot_instruction": "Enter your email to recover your password",
  "sent_link":"Send link",
  "send_link":"Reset link sent to email",
  "comunity_desc": "Our community is growing every day. Follow our updates to get the latest information about OVP tokens. Be with the future of the gaming industry, along with thousands of contributors.",
  "buy_tokens":"Buy tokens",
  "buy_tokens_for_fiat" :"Buy OVP tokens with fiat",
  "buy_for_fiat_desc": "To purchase OVP tokens for fiat money, you need to log in to your personal account. If you don't have an account yet, you need to register",
  "exchange_for_crypto":"OVP token exchange for cryptocurrency",
  "exchange_for_crypto_desc":"With the help of our exchanger, you can purchase OVP tokens for cryptocurrency or, on the contrary, embrace tokens by receiving cryptocurrency to your wallet.",
  "no_cypto_wallet":"Don't have a crypto wallet?",
  "no_cypto_wallet_desc":"If you don't have a crypto wallet yet, then watch our video tutorial",
  "exchange":"Exchange",
  "give":"Give",
  "recieve": "Recieve",
  "amount": "Amount",
  "price":"Price",
  "commision" : "Network commission 0.0065625 ETH",
  "transaction_time": "Expected arrival 5-30 minutes",
  "whole":"Total",
  "for":"for",
  "change_password": "Change password",
  "do_change_password": "Change",
  "wrong_link": "Wrong link",
  "please_connect_wallet":"Please connect your wallet first",
  "rejected_by_user": "Receted!",
  "too_low": "Too low",
  "done": "Exchange completed!",
  "please_wait": "Please wait 5-30 minutes and check your wallet!",
  "buy_for_fiat":"Buy OVP tokens with fiat",
  "do_buy_for_fiat_desc":"We accept VISA and Mastercard plastic cards. After the purchase, the tokens will be displayed on your balance. You can withdraw them to your crypto wallet at any time.",
  "on_your_balance":"On your balance",
  "fiat_commision":"Commission",
  "fiat_waite_time" : "Expected receipt of OVP tokens on the balance instantly",
  "do_buy_for_fiat":"Buy OVP",
  "withdraw":"Withdraw",
  "buy_for_fiat2":"Buying with fiat",
  "saved_wallets":"Saved wallets",
  "withdraw_to_wallet":"Withdraw to crypto wallet",
  "no_wallets_saved":"No saved wallets",
  "not_valide_amount":"Not correct amount",
  "withdrawed_to_wallet": "Withdrawn to crypto wallet",
  "company": "Company",
  "timeline": "Timeline",
  "how_to_buy": "How to buy",
  "swap_tokens": "Swap tokens",
  "intro_title":"OVP token is an investment in the future of the gaming industry",
  "intro_desc":"Become an early investor. Hurry up to buy a digital token from an established company in the fast growing and stable online gaming industry and get a fixed percentage of the profits.	",
  "industry":"Online gaming is the industry of the new time",
  "market_volume":"Market volumes",
  "market_text":"Games daily unite millions of people from all over the world. The online gaming industry is booming in the current environment. Before the pandemic, there were already 2.5 billion players in the world. Now, when many people are looking for ways to spend time at home and communicate without risk, interest in online games has grown significantly. Online gaming is a multi-million dollar fast-growing industry that is crisis-proof. Over the past 2 years alone, the volume of the gaming market has grown by almost $20 billion (19%) and amounted to $175.8 billion. The planned growth of the industry in 2022 is estimated at 20%",
  "company_about": "We are a full-cycle digital company that develops our own projects of online games and VR/AR applications: from creating the concept of revolutionary products, promotion on top trading platforms to full support and billing. We have a team of professionals led by high-class developers with rich experience in creating successful international games.",
  "design":"Design",
  "projecting":"Planning",
  "development":"Development",
  "diversification":"Diversification in gamedev",
  "marketing":"Marketing",
  "projects_managment":"Project management",
  "users_in_world":"Players around",
  "users_in_world2":"the world",
  "team_members":"Team of developers",
  "team_members2":"and game designers",
  "years_expirience":"Our company in",
  "years_expirience2":"the online games market",
  "mln":"mln",
  "men":"people",
  "years":"years",
  "cuurent_projects":"Current projects",
  "projects_lounched":"Project launched in 2019",
  "project1":"Massively multiplayer online role-playing game server developed and published by Blizzard Entertainment",
  "project1_link":"Go to project website",
  "prepering_to_lounch":"Ready for release",
  "projects2":"A complete free online universe with elements of a social network. The launch is being prepared for the third quarter of 2022",
  "development_proccess":"Development process",
  "modern_tech":"Modern technologies",
  "modern_tech_desc":"In our work we use the most advanced and promising technologies.",
  "gic_token":"OVP-token",
  "gic_token_desc":"Decentralized token that runs on the Ethereum ecosystem (ERC-20)",
  "gic_token_des2":"By issuing this token, we open the possibility of investing in our company for everyone (ICO). Investments will be used to scale the business and develop new promising online gaming projects. Thanks to our successful experience in online game development, understanding of business processes, market conditions and experience in working with a large gaming community, the investment will ultimately drive the value of the token and bring significant returns to early investors.",
  "token_desc3":"By purchasing a OVP token, investors become full co-owners of a part of our business and will receive a fixed percentage of our profits on an ongoing basis.",
  "token_name":"Token name",
  "token_symbol":"Token symbol",
  "total_supply":"Total minted",
  "circulation":"Offered for circulation",
  "smart_contract":"Smart contract",
  "format":"Token format",
  "investment_title":"Become an early investor and have time to acquire OVP tokens at a low price",
  "investment_desc":"The total supply of giktokens is capped at 25.000.000.000 equal to 25% shares of OVP-Only Virtual Projects",
  "investment_buy":"Buy tokens",
  "timeline_title": "Timeline",
  "timeline_desc": "Our development plans. We are focused on the future and results. For more information, please see our Whitepaper.",
  "timeline_point1": "Foundation of the company",
  "timeline_point2": "Launch of the first own project",
  "timeline_point3": "Start of development of the OVP token",
  "timeline_point4": "Withdrawal of the token to the ICO",
  "timeline_point5": "Launch of the Metaworld project",
  "timeline_point6": "Custom game development",
  "timeline_point7": "Starting the GICiumWoW Server",
  "timeline_point8": "Development of an economic model",
  "timeline_point9": "Listing of tokens on exchanges",
  "how_to_buy_title":"How to buy a OVP token",
  "how_to_buy_desc":"OVP tokens can be purchased on our website through an exchanger, in the future you will be able to purchase them on the exchange, but the price may increase significantly with our progress or the tokens will be sold out. OVP tokens can be purchased with fiat money, as well as for cryptocurrencies.",
  "how_to_buy_node":"Please note that not all wallets support the storage of OVP tokens. Please see",
  "how_to_buy_link":"list of supported wallets.",
  "how_to_buy_ques":"How to buy a OVP token?",
  "how_to_buy_ques2":"How to exchange? Where to store?",
  "for_crypto":"For cryptocurrency",
  "for_fiat":"For fiat",
  "instruction1":"Download a supported wallet",
  "instruction_desc1":"Create a wallet like Metamask using your desktop PC or download the app on your mobile phone. The wallet will allow you to buy, sell and send OVP tokens",
  "instruction2":"Fund your wallet with Ethereum",
  "instruction_desc2":"You can buy Ethereum directly from the wallet itself, or send it to it from the popular exchanges Coinbase, Binance, and others. Check that the network is selected ERC-20",
  "instruction3":"Connect your wallet to our exchanger",
  "instruction_desc3":"To do this, go to the exchanger, click connect wallet and select Metamask from the drop-down list of available wallets",
  "instruction4":"Exchange Ethereum for OVP Tokens",
  "instruction_desc4":"As soon as Ethereum is available on your wallet, you can buy OVP tokens. Please note that the tokens will be sent to the wallet from which the payment was made",
  "instruction5":"Register on the site",
  "instruction_desc5":"To buy tokens for fiat, register in our personal account",
  "instruction6":"Buy tokens",
  "instruction_desc6":"Pay with a plastic card (VISA/Mastercard) or any electronic payment system",
  "instruction7":"Withdraw tokens",
  "instruction_desc7":"Вы можете вывести токены на свой криптокошелек для хранения. Вывести их можно в любой момент времени.",
  "faq_title":"Popular questions",
  "faq_desc":"Check out popular questions and answers that can help you if you're having trouble",
  "faq_ans":"By issuing this token, we open the possibility of investing in our company for everyone (ICO). Investments will be used to scale the business and develop new promising online gaming projects.",
  "faq_ques1":"What is an ICO?",
  "faq_ques2":"How can I sell or donate OVP tokens?",
  "faq_ques3":"What does decentralized mean?",
  "faq_ques4":"I sent tokens to a non-existent address",
  "faq_ques5":"Where can I store OVP tokens?",
  "faq_ques6":"Why are only ERC-20 wallets supported?",
  "faq_ques7":"Can I buy tokens by paying with a VISA card?",
  "faq_ques8":"How can I sell or donate OVP tokens?",
  "choose_token":"Choose a token",
  "choose_desc":"Search for a token for exchange",
  "install_metamask": "Please install metemask extension",
  "select_currency": "Select currency",
  "banned": "Account blocked",
  "chat": "Chat with support",
  "send": "Send",
  "close_ticket": "Close ticket",
  "closed_ticket": "Closed",
  "admin_transaction": "Deposit by admin",
  "too_mach": "Too much",
  "delete": "Delete",
}